server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - name: GlobalFilter
              args:
                baseMessage: Spring Cloud Gateway WebFlux Global Filter
                preLogger: true
                postLogger: true

          routes:
            - id: user-service2
              uri: lb://user-service2
              predicates:
                - Path=/user-service2/**
            - id: catalog-service
              uri: lb://CATALOG-SERVICE
              predicates:
                - Path=/catalog-service/**
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/order-service/**
            - id: first-service
#              uri: http://localhost:8081/
              uri: lb://my-first-service
              predicates:
                - Path=/first-service/**
              filters:
#                - AddRequestHeader=f-request, 1st-request-header-by-yaml
#                - AddResponseHeader=f-response, 1st-response-header-from-yaml
                - CustomFilter

            - id: second-service
#              uri: http://localhost:8082/
              uri: lb://my-second-service
              predicates:
                - Path=/second-service/**
              filters:
#                - AddRequestHeader=s-request, 2nd-request-header-by-yaml
#                - AddResponseHeader=s-response, 2nd-response-header-from-yaml
                - name: CustomFilter
                - name: LoggingFilter
                  args:
                    baseMessage: Hi, LoggingFilter.
                    preLogger: true
                    postLogger: true



